package cn.mcandroid.stus;

public class Stus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stus.id
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stus.name
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stus.sex
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stus.id
     *
     * @return the value of stus.id
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stus.id
     *
     * @param id the value for stus.id
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stus.name
     *
     * @return the value of stus.name
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stus.name
     *
     * @param name the value for stus.name
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stus.sex
     *
     * @return the value of stus.sex
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stus.sex
     *
     * @param sex the value for stus.sex
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

	@Override
	public String toString() {
		return this.id+","+this.name+","+this.sex;
	}
    
    
    
}