package cn.mcandroid.dao;

import cn.mcandroid.stus.Stus;
import cn.mcandroid.stus.StusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    long countByExample(StusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int deleteByExample(StusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int insert(Stus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int insertSelective(Stus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    List<Stus> selectByExample(StusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    Stus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Stus record, @Param("example") StusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int updateByExample(@Param("record") Stus record, @Param("example") StusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int updateByPrimaryKeySelective(Stus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stus
     *
     * @mbg.generated Wed Nov 21 11:02:39 CST 2018
     */
    int updateByPrimaryKey(Stus record);
}